### PR TITLE
Fix handling of multi-message TSIG responses

### LINKED ISSUE #295: bug with TSIG verification of large responses
We've encountered a bug with how DNSJAVA verifies the transaction signature of large responses.

In our environment, we can successfully perform an AXFR for a small zone (22 line zone file, 2096 bytes on the wire).  But we get a TSIG related error (org.xbill.DNS.ZoneTransferException: TSIG failure: BADSIG) when transferring a larger zone (7855 line zone file,  400k on the wire).

This bug was introduced between versions 3.1.0 and 3.20.  The TSIG class saw a significant rework there, and the interactions between the TSIG.StreamVerifier class and the TSIG.verify() method were broken then -- although seemingly only in cases where the signed response encompassed multiple messages.

While investigating this, we developed a patch for 3.5.2 this that we would be happy to submit as a pull request (or, really, help get this fixed some other way).

### PR DESCRIPTION
**Pull request by ibauersachs**
Closes #295
Closes #297
Closes #298
Closes #299
Closes #301

### CODE REVIEW

**Comment by frankarinnet** [comment]
I'm afraid its not quite right.  In this case, there is still a bug with verify process (and a symmetric bug with the generate process).  The signature of the TSIG record isn't being added at quite the right time (as usual only in the case of mixed signed/unsigned messages).

On the bright side, the bug is much more narrow at this point.

I've got a branch of 'tsig-stream' I'll submit shortly as another PR.

File: src/main/java/org/xbill/DNS/TSIG.java [hunk 1]
```diff
@@ -749,15 +849,16 @@ public int verify(Message m, byte[] b) {
...
-        lastTSIG = tsig;
+        int result = key.verify(m, b, queryTsig, true, sharedHmac);
+        hmacAddSignature(sharedHmac, tsig);
+        lastsigned = nresponses;
         return result;
       }
 
       if (tsig != null) {
-        int result = key.verify(m, b, lastTSIG, false);
+        int result = key.verify(m, b, null, false, sharedHmac);
```
Comment (frankarinnet) [inline src/main/java/org/xbill/DNS/TSIG.java:859]: Very clever.  I think this satisfies all my concerns about backward compatibility.
